services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: cinema-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    container_name: cinema-azurite
    command: "azurite --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost 0.0.0.0 --loose"
    ports:
      - "10000:10000"   # Blob
      - "10001:10001"   # Queue
      - "10002:10002"   # Table
    volumes:
      - azurite-data:/data

volumes:
  sqlserver-data:
  azurite-data: